// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P02Travel.API.Models;

#nullable disable

namespace P02Travel.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231107233723_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P03Travel.Shared.Travels.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airlines")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 49, 36, 37, DateTimeKind.Local).AddTicks(2930),
                            From = "XGG",
                            Price = 402,
                            To = "GWZ"
                        },
                        new
                        {
                            Id = 2,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 16, 56, 591, DateTimeKind.Local).AddTicks(6729),
                            From = "AJJ",
                            Price = 459,
                            To = "PDH"
                        },
                        new
                        {
                            Id = 3,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 35, 39, 619, DateTimeKind.Local).AddTicks(2253),
                            From = "SOB",
                            Price = 477,
                            To = "PJS"
                        },
                        new
                        {
                            Id = 4,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 47, 30, 352, DateTimeKind.Local).AddTicks(8272),
                            From = "DRP",
                            Price = 426,
                            To = "GCF"
                        },
                        new
                        {
                            Id = 5,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 8, 47, 43, 347, DateTimeKind.Local).AddTicks(3497),
                            From = "KHH",
                            Price = 422,
                            To = "KHR"
                        },
                        new
                        {
                            Id = 6,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 2, 46, 42, 666, DateTimeKind.Local).AddTicks(5996),
                            From = "ATU",
                            Price = 152,
                            To = "EAG"
                        },
                        new
                        {
                            Id = 7,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 4, 44, 249, DateTimeKind.Local).AddTicks(5297),
                            From = "BGX",
                            Price = 402,
                            To = "NIG"
                        },
                        new
                        {
                            Id = 8,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 14, 49, 105, DateTimeKind.Local).AddTicks(3480),
                            From = "GTH",
                            Price = 438,
                            To = "DUR"
                        },
                        new
                        {
                            Id = 9,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 23, 9, 6, 875, DateTimeKind.Local).AddTicks(1709),
                            From = "AIH",
                            Price = 245,
                            To = "IUA"
                        },
                        new
                        {
                            Id = 10,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 18, 37, 25, 445, DateTimeKind.Local).AddTicks(4994),
                            From = "JZQ",
                            Price = 341,
                            To = "ICZ"
                        },
                        new
                        {
                            Id = 11,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 16, 26, 643, DateTimeKind.Local).AddTicks(924),
                            From = "OWY",
                            Price = 441,
                            To = "AQR"
                        },
                        new
                        {
                            Id = 12,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 3, 18, 36, 599, DateTimeKind.Local).AddTicks(136),
                            From = "BWY",
                            Price = 129,
                            To = "DIN"
                        },
                        new
                        {
                            Id = 13,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 9, 51, 2, 3, DateTimeKind.Local).AddTicks(1990),
                            From = "IRL",
                            Price = 257,
                            To = "WEJ"
                        },
                        new
                        {
                            Id = 14,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 7, 17, 23, 831, DateTimeKind.Local).AddTicks(3891),
                            From = "EYQ",
                            Price = 320,
                            To = "HNB"
                        },
                        new
                        {
                            Id = 15,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 7, 54, 47, 257, DateTimeKind.Local).AddTicks(2834),
                            From = "GZQ",
                            Price = 288,
                            To = "PMH"
                        },
                        new
                        {
                            Id = 16,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 6, 50, 46, 546, DateTimeKind.Local).AddTicks(4714),
                            From = "XFQ",
                            Price = 193,
                            To = "DGA"
                        },
                        new
                        {
                            Id = 17,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 58, 24, 259, DateTimeKind.Local).AddTicks(3826),
                            From = "RRQ",
                            Price = 127,
                            To = "OQH"
                        },
                        new
                        {
                            Id = 18,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 31, 21, 270, DateTimeKind.Local).AddTicks(2311),
                            From = "XSH",
                            Price = 467,
                            To = "WOB"
                        },
                        new
                        {
                            Id = 19,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 2, 30, 899, DateTimeKind.Local).AddTicks(9482),
                            From = "DSF",
                            Price = 222,
                            To = "DKX"
                        },
                        new
                        {
                            Id = 20,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 43, 55, 212, DateTimeKind.Local).AddTicks(4729),
                            From = "YAR",
                            Price = 111,
                            To = "QBH"
                        },
                        new
                        {
                            Id = 21,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 14, 26, 22, 888, DateTimeKind.Local).AddTicks(2174),
                            From = "YQI",
                            Price = 386,
                            To = "INU"
                        },
                        new
                        {
                            Id = 22,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 3, 20, 38, 318, DateTimeKind.Local).AddTicks(2187),
                            From = "TBQ",
                            Price = 448,
                            To = "PFK"
                        },
                        new
                        {
                            Id = 23,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 3, 32, 9, 826, DateTimeKind.Local).AddTicks(3986),
                            From = "UNH",
                            Price = 159,
                            To = "TGE"
                        },
                        new
                        {
                            Id = 24,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 9, 0, 1, 48, 74, DateTimeKind.Local).AddTicks(942),
                            From = "XFR",
                            Price = 283,
                            To = "AWS"
                        },
                        new
                        {
                            Id = 25,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 13, 26, 335, DateTimeKind.Local).AddTicks(3337),
                            From = "TTE",
                            Price = 233,
                            To = "JLU"
                        },
                        new
                        {
                            Id = 26,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 5, 10, 40, 243, DateTimeKind.Local).AddTicks(2697),
                            From = "MIU",
                            Price = 406,
                            To = "GTY"
                        },
                        new
                        {
                            Id = 27,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 32, 36, 272, DateTimeKind.Local).AddTicks(6499),
                            From = "HDK",
                            Price = 168,
                            To = "EFK"
                        },
                        new
                        {
                            Id = 28,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 2, 17, 39, 3, DateTimeKind.Local).AddTicks(3369),
                            From = "WTF",
                            Price = 210,
                            To = "XEG"
                        },
                        new
                        {
                            Id = 29,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 21, 27, 577, DateTimeKind.Local).AddTicks(4360),
                            From = "ILC",
                            Price = 397,
                            To = "LLS"
                        },
                        new
                        {
                            Id = 30,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 4, 32, 41, 608, DateTimeKind.Local).AddTicks(2011),
                            From = "WPK",
                            Price = 285,
                            To = "SGQ"
                        },
                        new
                        {
                            Id = 31,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 52, 6, 643, DateTimeKind.Local).AddTicks(4429),
                            From = "SPO",
                            Price = 292,
                            To = "TFP"
                        },
                        new
                        {
                            Id = 32,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 9, 48, 534, DateTimeKind.Local).AddTicks(2967),
                            From = "FOD",
                            Price = 346,
                            To = "NZS"
                        },
                        new
                        {
                            Id = 33,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 8, 23, 33, 221, DateTimeKind.Local).AddTicks(8738),
                            From = "EUQ",
                            Price = 347,
                            To = "RKN"
                        },
                        new
                        {
                            Id = 34,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 39, 13, 486, DateTimeKind.Local).AddTicks(8432),
                            From = "XDM",
                            Price = 267,
                            To = "NLA"
                        },
                        new
                        {
                            Id = 35,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 59, 6, 902, DateTimeKind.Local).AddTicks(3105),
                            From = "TNG",
                            Price = 490,
                            To = "MZZ"
                        },
                        new
                        {
                            Id = 36,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 7, 45, 52, 978, DateTimeKind.Local).AddTicks(99),
                            From = "QHP",
                            Price = 469,
                            To = "RCU"
                        },
                        new
                        {
                            Id = 37,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 14, 13, 0, 930, DateTimeKind.Local).AddTicks(6883),
                            From = "DBF",
                            Price = 258,
                            To = "AEX"
                        },
                        new
                        {
                            Id = 38,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 50, 14, 624, DateTimeKind.Local).AddTicks(8812),
                            From = "GQD",
                            Price = 217,
                            To = "DDL"
                        },
                        new
                        {
                            Id = 39,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 23, 55, 4, 210, DateTimeKind.Local).AddTicks(2408),
                            From = "MQW",
                            Price = 289,
                            To = "QRX"
                        },
                        new
                        {
                            Id = 40,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 6, 53, 37, 289, DateTimeKind.Local).AddTicks(4483),
                            From = "OFA",
                            Price = 368,
                            To = "RPD"
                        },
                        new
                        {
                            Id = 41,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 17, 55, 39, 985, DateTimeKind.Local).AddTicks(8987),
                            From = "FSJ",
                            Price = 366,
                            To = "JCK"
                        },
                        new
                        {
                            Id = 42,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 13, 28, 240, DateTimeKind.Local).AddTicks(1760),
                            From = "YMD",
                            Price = 468,
                            To = "EKG"
                        },
                        new
                        {
                            Id = 43,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 46, 37, 337, DateTimeKind.Local).AddTicks(8849),
                            From = "MLI",
                            Price = 442,
                            To = "HNE"
                        },
                        new
                        {
                            Id = 44,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 2, 24, 52, 747, DateTimeKind.Local).AddTicks(4944),
                            From = "HNB",
                            Price = 484,
                            To = "ZLW"
                        },
                        new
                        {
                            Id = 45,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 34, 18, 937, DateTimeKind.Local).AddTicks(7778),
                            From = "MCN",
                            Price = 126,
                            To = "KAZ"
                        },
                        new
                        {
                            Id = 46,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 4, 56, 33, 181, DateTimeKind.Local).AddTicks(7846),
                            From = "WKT",
                            Price = 305,
                            To = "STE"
                        },
                        new
                        {
                            Id = 47,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 9, 4, 41, 629, DateTimeKind.Local).AddTicks(3411),
                            From = "DXE",
                            Price = 124,
                            To = "EMH"
                        },
                        new
                        {
                            Id = 48,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 22, 20, 825, DateTimeKind.Local).AddTicks(1548),
                            From = "TYA",
                            Price = 171,
                            To = "HFI"
                        },
                        new
                        {
                            Id = 49,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 0, 11, 6, 144, DateTimeKind.Local).AddTicks(5630),
                            From = "CBL",
                            Price = 388,
                            To = "IGA"
                        },
                        new
                        {
                            Id = 50,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 59, 42, 85, DateTimeKind.Local).AddTicks(1144),
                            From = "OOT",
                            Price = 136,
                            To = "WLH"
                        },
                        new
                        {
                            Id = 51,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 7, 9, 47, 420, DateTimeKind.Local).AddTicks(7094),
                            From = "XIP",
                            Price = 429,
                            To = "FJQ"
                        },
                        new
                        {
                            Id = 52,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 52, 37, 888, DateTimeKind.Local).AddTicks(7699),
                            From = "LOF",
                            Price = 444,
                            To = "LOJ"
                        },
                        new
                        {
                            Id = 53,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 35, 51, 89, DateTimeKind.Local).AddTicks(983),
                            From = "ITQ",
                            Price = 478,
                            To = "ELN"
                        },
                        new
                        {
                            Id = 54,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 7, 20, 42, 180, DateTimeKind.Local).AddTicks(9915),
                            From = "JYL",
                            Price = 169,
                            To = "REK"
                        },
                        new
                        {
                            Id = 55,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 6, 58, 16, 163, DateTimeKind.Local).AddTicks(5090),
                            From = "SWR",
                            Price = 266,
                            To = "UNZ"
                        },
                        new
                        {
                            Id = 56,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 8, 7, 974, DateTimeKind.Local).AddTicks(1204),
                            From = "DCZ",
                            Price = 173,
                            To = "KZB"
                        },
                        new
                        {
                            Id = 57,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 1, 51, 590, DateTimeKind.Local).AddTicks(2580),
                            From = "MRW",
                            Price = 449,
                            To = "BHW"
                        },
                        new
                        {
                            Id = 58,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 3, 54, 46, 978, DateTimeKind.Local).AddTicks(3611),
                            From = "DSK",
                            Price = 216,
                            To = "UHH"
                        },
                        new
                        {
                            Id = 59,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 42, 34, 97, DateTimeKind.Local).AddTicks(5788),
                            From = "KMG",
                            Price = 155,
                            To = "RTF"
                        },
                        new
                        {
                            Id = 60,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 58, 23, 627, DateTimeKind.Local).AddTicks(5314),
                            From = "TZY",
                            Price = 257,
                            To = "KNK"
                        },
                        new
                        {
                            Id = 61,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 7, 27, 58, 914, DateTimeKind.Local).AddTicks(9034),
                            From = "FQN",
                            Price = 353,
                            To = "UYC"
                        },
                        new
                        {
                            Id = 62,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 2, 42, 985, DateTimeKind.Local).AddTicks(9103),
                            From = "ZIU",
                            Price = 287,
                            To = "RCW"
                        },
                        new
                        {
                            Id = 63,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 2, 21, 45, 369, DateTimeKind.Local).AddTicks(8969),
                            From = "STY",
                            Price = 288,
                            To = "QYM"
                        },
                        new
                        {
                            Id = 64,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 2, 10, 32, 700, DateTimeKind.Local).AddTicks(399),
                            From = "KRF",
                            Price = 390,
                            To = "ZKP"
                        },
                        new
                        {
                            Id = 65,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 4, 12, 17, 875, DateTimeKind.Local).AddTicks(5887),
                            From = "AOO",
                            Price = 370,
                            To = "EBM"
                        },
                        new
                        {
                            Id = 66,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 11, 48, 431, DateTimeKind.Local).AddTicks(702),
                            From = "OCW",
                            Price = 166,
                            To = "BYT"
                        },
                        new
                        {
                            Id = 67,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 6, 9, 22, 746, DateTimeKind.Local).AddTicks(8448),
                            From = "POR",
                            Price = 359,
                            To = "BJW"
                        },
                        new
                        {
                            Id = 68,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 1, 57, 582, DateTimeKind.Local).AddTicks(1527),
                            From = "IAX",
                            Price = 249,
                            To = "FZB"
                        },
                        new
                        {
                            Id = 69,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 21, 54, 30, 522, DateTimeKind.Local).AddTicks(875),
                            From = "QOR",
                            Price = 113,
                            To = "LZT"
                        },
                        new
                        {
                            Id = 70,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 2, 55, 5, 269, DateTimeKind.Local).AddTicks(5381),
                            From = "OIT",
                            Price = 386,
                            To = "KUT"
                        },
                        new
                        {
                            Id = 71,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 8, 57, 57, 598, DateTimeKind.Local).AddTicks(6487),
                            From = "TZF",
                            Price = 467,
                            To = "SNW"
                        },
                        new
                        {
                            Id = 72,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 41, 44, 230, DateTimeKind.Local).AddTicks(7980),
                            From = "OJD",
                            Price = 333,
                            To = "URM"
                        },
                        new
                        {
                            Id = 73,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 2, 8, 48, 701, DateTimeKind.Local).AddTicks(4980),
                            From = "EEO",
                            Price = 455,
                            To = "YAL"
                        },
                        new
                        {
                            Id = 74,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 14, 55, 22, 646, DateTimeKind.Local).AddTicks(3740),
                            From = "TXE",
                            Price = 324,
                            To = "DMW"
                        },
                        new
                        {
                            Id = 75,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 51, 45, 672, DateTimeKind.Local).AddTicks(5719),
                            From = "ZYB",
                            Price = 358,
                            To = "WNP"
                        },
                        new
                        {
                            Id = 76,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 39, 5, 985, DateTimeKind.Local).AddTicks(5411),
                            From = "WTP",
                            Price = 382,
                            To = "GWH"
                        },
                        new
                        {
                            Id = 77,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 3, 27, 21, 598, DateTimeKind.Local).AddTicks(6932),
                            From = "XWZ",
                            Price = 475,
                            To = "SWL"
                        },
                        new
                        {
                            Id = 78,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 26, 27, 628, DateTimeKind.Local).AddTicks(9004),
                            From = "YLW",
                            Price = 126,
                            To = "GGC"
                        },
                        new
                        {
                            Id = 79,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 1, 38, 32, 324, DateTimeKind.Local).AddTicks(2703),
                            From = "AHP",
                            Price = 485,
                            To = "ZHN"
                        },
                        new
                        {
                            Id = 80,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 34, 22, 86, DateTimeKind.Local).AddTicks(4664),
                            From = "HNB",
                            Price = 483,
                            To = "WKY"
                        },
                        new
                        {
                            Id = 81,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 17, 15, 44, 96, DateTimeKind.Local).AddTicks(9850),
                            From = "LFC",
                            Price = 170,
                            To = "OYK"
                        },
                        new
                        {
                            Id = 82,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 17, 5, 13, 750, DateTimeKind.Local).AddTicks(5355),
                            From = "QOM",
                            Price = 397,
                            To = "MEF"
                        },
                        new
                        {
                            Id = 83,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 19, 12, 302, DateTimeKind.Local).AddTicks(6690),
                            From = "HYO",
                            Price = 164,
                            To = "KTU"
                        },
                        new
                        {
                            Id = 84,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 14, 59, 7, 986, DateTimeKind.Local).AddTicks(4615),
                            From = "KBA",
                            Price = 245,
                            To = "YHO"
                        },
                        new
                        {
                            Id = 85,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 8, 20, 19, 217, DateTimeKind.Local).AddTicks(5901),
                            From = "MKI",
                            Price = 308,
                            To = "FTO"
                        },
                        new
                        {
                            Id = 86,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 34, 41, 305, DateTimeKind.Local).AddTicks(5997),
                            From = "TTI",
                            Price = 381,
                            To = "UDS"
                        },
                        new
                        {
                            Id = 87,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 6, 44, 685, DateTimeKind.Local).AddTicks(7310),
                            From = "EAL",
                            Price = 437,
                            To = "HKH"
                        },
                        new
                        {
                            Id = 88,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 6, 41, 30, 650, DateTimeKind.Local).AddTicks(2703),
                            From = "ZRH",
                            Price = 436,
                            To = "XDO"
                        },
                        new
                        {
                            Id = 89,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 9, 36, 35, 132, DateTimeKind.Local).AddTicks(7883),
                            From = "XBD",
                            Price = 243,
                            To = "ZXL"
                        },
                        new
                        {
                            Id = 90,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 5, 11, 58, 863, DateTimeKind.Local).AddTicks(3937),
                            From = "FOY",
                            Price = 442,
                            To = "HFP"
                        },
                        new
                        {
                            Id = 91,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 8, 11, 470, DateTimeKind.Local).AddTicks(4887),
                            From = "YFZ",
                            Price = 487,
                            To = "BJA"
                        },
                        new
                        {
                            Id = 92,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 48, 50, 615, DateTimeKind.Local).AddTicks(2702),
                            From = "DWP",
                            Price = 287,
                            To = "SZX"
                        },
                        new
                        {
                            Id = 93,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 18, 20, 814, DateTimeKind.Local).AddTicks(7817),
                            From = "PED",
                            Price = 260,
                            To = "ZYB"
                        },
                        new
                        {
                            Id = 94,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 22, 0, 13, 729, DateTimeKind.Local).AddTicks(7897),
                            From = "RRM",
                            Price = 112,
                            To = "QBZ"
                        },
                        new
                        {
                            Id = 95,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 5, 42, 41, 557, DateTimeKind.Local).AddTicks(5319),
                            From = "GWR",
                            Price = 443,
                            To = "CAJ"
                        },
                        new
                        {
                            Id = 96,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 6, 43, 13, 778, DateTimeKind.Local).AddTicks(7907),
                            From = "GLP",
                            Price = 116,
                            To = "BUK"
                        },
                        new
                        {
                            Id = 97,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 7, 27, 28, 178, DateTimeKind.Local).AddTicks(8391),
                            From = "LZH",
                            Price = 437,
                            To = "YQS"
                        },
                        new
                        {
                            Id = 98,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 5, 6, 55, 856, DateTimeKind.Local).AddTicks(2774),
                            From = "CLU",
                            Price = 436,
                            To = "QSC"
                        },
                        new
                        {
                            Id = 99,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 3, 30, 46, 90, DateTimeKind.Local).AddTicks(8703),
                            From = "WME",
                            Price = 323,
                            To = "SDR"
                        },
                        new
                        {
                            Id = 100,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 14, 42, 16, 253, DateTimeKind.Local).AddTicks(7261),
                            From = "OPW",
                            Price = 484,
                            To = "CPU"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
