// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P02Travel.API.Models;

#nullable disable

namespace P02Travel.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P03Travel.Shared.Travels.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airlines")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 22, 17, 48, 815, DateTimeKind.Local).AddTicks(1716),
                            From = "XGG",
                            Price = 402,
                            To = "GWZ"
                        },
                        new
                        {
                            Id = 2,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 45, 9, 369, DateTimeKind.Local).AddTicks(5047),
                            From = "AJJ",
                            Price = 459,
                            To = "PDH"
                        },
                        new
                        {
                            Id = 3,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 0, 3, 52, 397, DateTimeKind.Local).AddTicks(569),
                            From = "SOB",
                            Price = 477,
                            To = "PJS"
                        },
                        new
                        {
                            Id = 4,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 15, 43, 130, DateTimeKind.Local).AddTicks(6588),
                            From = "DRP",
                            Price = 426,
                            To = "GCF"
                        },
                        new
                        {
                            Id = 5,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 17, 15, 56, 125, DateTimeKind.Local).AddTicks(1855),
                            From = "KHH",
                            Price = 422,
                            To = "KHR"
                        },
                        new
                        {
                            Id = 6,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 14, 55, 444, DateTimeKind.Local).AddTicks(4355),
                            From = "ATU",
                            Price = 152,
                            To = "EAG"
                        },
                        new
                        {
                            Id = 7,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 23, 32, 57, 27, DateTimeKind.Local).AddTicks(3655),
                            From = "BGX",
                            Price = 402,
                            To = "NIG"
                        },
                        new
                        {
                            Id = 8,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 43, 1, 883, DateTimeKind.Local).AddTicks(1838),
                            From = "GTH",
                            Price = 438,
                            To = "DUR"
                        },
                        new
                        {
                            Id = 9,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 7, 37, 19, 653, DateTimeKind.Local).AddTicks(67),
                            From = "AIH",
                            Price = 245,
                            To = "IUA"
                        },
                        new
                        {
                            Id = 10,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 9, 3, 5, 38, 223, DateTimeKind.Local).AddTicks(3351),
                            From = "JZQ",
                            Price = 341,
                            To = "ICZ"
                        },
                        new
                        {
                            Id = 11,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 21, 44, 39, 420, DateTimeKind.Local).AddTicks(9281),
                            From = "OWY",
                            Price = 441,
                            To = "AQR"
                        },
                        new
                        {
                            Id = 12,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 46, 49, 376, DateTimeKind.Local).AddTicks(8493),
                            From = "BWY",
                            Price = 129,
                            To = "DIN"
                        },
                        new
                        {
                            Id = 13,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 18, 19, 14, 781, DateTimeKind.Local).AddTicks(347),
                            From = "IRL",
                            Price = 257,
                            To = "WEJ"
                        },
                        new
                        {
                            Id = 14,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 45, 36, 609, DateTimeKind.Local).AddTicks(2248),
                            From = "EYQ",
                            Price = 320,
                            To = "HNB"
                        },
                        new
                        {
                            Id = 15,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 23, 0, 35, DateTimeKind.Local).AddTicks(1191),
                            From = "GZQ",
                            Price = 288,
                            To = "PMH"
                        },
                        new
                        {
                            Id = 16,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 18, 59, 324, DateTimeKind.Local).AddTicks(3070),
                            From = "XFQ",
                            Price = 193,
                            To = "DGA"
                        },
                        new
                        {
                            Id = 17,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 9, 1, 26, 37, 37, DateTimeKind.Local).AddTicks(2181),
                            From = "RRQ",
                            Price = 127,
                            To = "OQH"
                        },
                        new
                        {
                            Id = 18,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 9, 4, 59, 34, 48, DateTimeKind.Local).AddTicks(667),
                            From = "XSH",
                            Price = 467,
                            To = "WOB"
                        },
                        new
                        {
                            Id = 19,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 30, 43, 677, DateTimeKind.Local).AddTicks(7838),
                            From = "DSF",
                            Price = 222,
                            To = "DKX"
                        },
                        new
                        {
                            Id = 20,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 9, 5, 12, 7, 990, DateTimeKind.Local).AddTicks(3084),
                            From = "YAR",
                            Price = 111,
                            To = "QBH"
                        },
                        new
                        {
                            Id = 21,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 22, 54, 35, 666, DateTimeKind.Local).AddTicks(528),
                            From = "YQI",
                            Price = 386,
                            To = "INU"
                        },
                        new
                        {
                            Id = 22,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 48, 51, 96, DateTimeKind.Local).AddTicks(542),
                            From = "TBQ",
                            Price = 448,
                            To = "PFK"
                        },
                        new
                        {
                            Id = 23,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 0, 22, 604, DateTimeKind.Local).AddTicks(2339),
                            From = "UNH",
                            Price = 159,
                            To = "TGE"
                        },
                        new
                        {
                            Id = 24,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 9, 8, 30, 0, 851, DateTimeKind.Local).AddTicks(9296),
                            From = "XFR",
                            Price = 283,
                            To = "AWS"
                        },
                        new
                        {
                            Id = 25,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 21, 41, 39, 113, DateTimeKind.Local).AddTicks(1690),
                            From = "TTE",
                            Price = 233,
                            To = "JLU"
                        },
                        new
                        {
                            Id = 26,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 38, 53, 21, DateTimeKind.Local).AddTicks(1050),
                            From = "MIU",
                            Price = 406,
                            To = "GTY"
                        },
                        new
                        {
                            Id = 27,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 5, 0, 49, 50, DateTimeKind.Local).AddTicks(4852),
                            From = "HDK",
                            Price = 168,
                            To = "EFK"
                        },
                        new
                        {
                            Id = 28,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 45, 51, 781, DateTimeKind.Local).AddTicks(1722),
                            From = "WTF",
                            Price = 210,
                            To = "XEG"
                        },
                        new
                        {
                            Id = 29,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 9, 0, 49, 40, 355, DateTimeKind.Local).AddTicks(2671),
                            From = "ILC",
                            Price = 397,
                            To = "LLS"
                        },
                        new
                        {
                            Id = 30,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 0, 54, 386, DateTimeKind.Local).AddTicks(321),
                            From = "WPK",
                            Price = 285,
                            To = "SGQ"
                        },
                        new
                        {
                            Id = 31,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 20, 19, 421, DateTimeKind.Local).AddTicks(2738),
                            From = "SPO",
                            Price = 292,
                            To = "TFP"
                        },
                        new
                        {
                            Id = 32,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 38, 1, 312, DateTimeKind.Local).AddTicks(1276),
                            From = "FOD",
                            Price = 346,
                            To = "NZS"
                        },
                        new
                        {
                            Id = 33,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 51, 45, 999, DateTimeKind.Local).AddTicks(7046),
                            From = "EUQ",
                            Price = 347,
                            To = "RKN"
                        },
                        new
                        {
                            Id = 34,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 22, 7, 26, 264, DateTimeKind.Local).AddTicks(6741),
                            From = "XDM",
                            Price = 267,
                            To = "NLA"
                        },
                        new
                        {
                            Id = 35,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 21, 27, 19, 680, DateTimeKind.Local).AddTicks(1414),
                            From = "TNG",
                            Price = 490,
                            To = "MZZ"
                        },
                        new
                        {
                            Id = 36,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 14, 5, 755, DateTimeKind.Local).AddTicks(8407),
                            From = "QHP",
                            Price = 469,
                            To = "RCU"
                        },
                        new
                        {
                            Id = 37,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 22, 41, 13, 708, DateTimeKind.Local).AddTicks(5221),
                            From = "DBF",
                            Price = 258,
                            To = "AEX"
                        },
                        new
                        {
                            Id = 38,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 9, 5, 18, 27, 402, DateTimeKind.Local).AddTicks(7151),
                            From = "GQD",
                            Price = 217,
                            To = "DDL"
                        },
                        new
                        {
                            Id = 39,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 9, 8, 23, 16, 988, DateTimeKind.Local).AddTicks(747),
                            From = "MQW",
                            Price = 289,
                            To = "QRX"
                        },
                        new
                        {
                            Id = 40,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 21, 50, 67, DateTimeKind.Local).AddTicks(2822),
                            From = "OFA",
                            Price = 368,
                            To = "RPD"
                        },
                        new
                        {
                            Id = 41,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 9, 2, 23, 52, 763, DateTimeKind.Local).AddTicks(7326),
                            From = "FSJ",
                            Price = 366,
                            To = "JCK"
                        },
                        new
                        {
                            Id = 42,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 41, 41, 18, DateTimeKind.Local).AddTicks(99),
                            From = "YMD",
                            Price = 468,
                            To = "EKG"
                        },
                        new
                        {
                            Id = 43,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 9, 4, 14, 50, 115, DateTimeKind.Local).AddTicks(7188),
                            From = "MLI",
                            Price = 442,
                            To = "HNE"
                        },
                        new
                        {
                            Id = 44,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 53, 5, 525, DateTimeKind.Local).AddTicks(3284),
                            From = "HNB",
                            Price = 484,
                            To = "ZLW"
                        },
                        new
                        {
                            Id = 45,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 22, 2, 31, 715, DateTimeKind.Local).AddTicks(6118),
                            From = "MCN",
                            Price = 126,
                            To = "KAZ"
                        },
                        new
                        {
                            Id = 46,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 24, 45, 959, DateTimeKind.Local).AddTicks(6185),
                            From = "WKT",
                            Price = 305,
                            To = "STE"
                        },
                        new
                        {
                            Id = 47,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 17, 32, 54, 407, DateTimeKind.Local).AddTicks(1749),
                            From = "DXE",
                            Price = 124,
                            To = "EMH"
                        },
                        new
                        {
                            Id = 48,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 18, 50, 33, 602, DateTimeKind.Local).AddTicks(9886),
                            From = "TYA",
                            Price = 171,
                            To = "HFI"
                        },
                        new
                        {
                            Id = 49,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 8, 39, 18, 922, DateTimeKind.Local).AddTicks(3968),
                            From = "CBL",
                            Price = 388,
                            To = "IGA"
                        },
                        new
                        {
                            Id = 50,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 9, 4, 27, 54, 862, DateTimeKind.Local).AddTicks(9482),
                            From = "OOT",
                            Price = 136,
                            To = "WLH"
                        },
                        new
                        {
                            Id = 51,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 38, 0, 198, DateTimeKind.Local).AddTicks(5432),
                            From = "XIP",
                            Price = 429,
                            To = "FJQ"
                        },
                        new
                        {
                            Id = 52,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 20, 50, 666, DateTimeKind.Local).AddTicks(6036),
                            From = "LOF",
                            Price = 444,
                            To = "LOJ"
                        },
                        new
                        {
                            Id = 53,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 21, 4, 3, 866, DateTimeKind.Local).AddTicks(9321),
                            From = "ITQ",
                            Price = 478,
                            To = "ELN"
                        },
                        new
                        {
                            Id = 54,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 48, 54, 958, DateTimeKind.Local).AddTicks(8253),
                            From = "JYL",
                            Price = 169,
                            To = "REK"
                        },
                        new
                        {
                            Id = 55,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 26, 28, 941, DateTimeKind.Local).AddTicks(3428),
                            From = "SWR",
                            Price = 266,
                            To = "UNZ"
                        },
                        new
                        {
                            Id = 56,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 9, 3, 36, 20, 751, DateTimeKind.Local).AddTicks(9542),
                            From = "DCZ",
                            Price = 173,
                            To = "KZB"
                        },
                        new
                        {
                            Id = 57,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 30, 4, 368, DateTimeKind.Local).AddTicks(917),
                            From = "MRW",
                            Price = 449,
                            To = "BHW"
                        },
                        new
                        {
                            Id = 58,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 22, 59, 756, DateTimeKind.Local).AddTicks(1949),
                            From = "DSK",
                            Price = 216,
                            To = "UHH"
                        },
                        new
                        {
                            Id = 59,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 9, 4, 10, 46, 875, DateTimeKind.Local).AddTicks(4126),
                            From = "KMG",
                            Price = 155,
                            To = "RTF"
                        },
                        new
                        {
                            Id = 60,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 9, 1, 26, 36, 405, DateTimeKind.Local).AddTicks(3623),
                            From = "TZY",
                            Price = 257,
                            To = "KNK"
                        },
                        new
                        {
                            Id = 61,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 56, 11, 692, DateTimeKind.Local).AddTicks(7341),
                            From = "FQN",
                            Price = 353,
                            To = "UYC"
                        },
                        new
                        {
                            Id = 62,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 9, 3, 30, 55, 763, DateTimeKind.Local).AddTicks(7410),
                            From = "ZIU",
                            Price = 287,
                            To = "RCW"
                        },
                        new
                        {
                            Id = 63,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 49, 58, 147, DateTimeKind.Local).AddTicks(7276),
                            From = "STY",
                            Price = 288,
                            To = "QYM"
                        },
                        new
                        {
                            Id = 64,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 38, 45, 477, DateTimeKind.Local).AddTicks(8705),
                            From = "KRF",
                            Price = 390,
                            To = "ZKP"
                        },
                        new
                        {
                            Id = 65,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 12, 40, 30, 653, DateTimeKind.Local).AddTicks(4192),
                            From = "AOO",
                            Price = 370,
                            To = "EBM"
                        },
                        new
                        {
                            Id = 66,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 9, 0, 40, 1, 208, DateTimeKind.Local).AddTicks(9007),
                            From = "OCW",
                            Price = 166,
                            To = "BYT"
                        },
                        new
                        {
                            Id = 67,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 14, 37, 35, 524, DateTimeKind.Local).AddTicks(6754),
                            From = "POR",
                            Price = 359,
                            To = "BJW"
                        },
                        new
                        {
                            Id = 68,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 19, 30, 10, 359, DateTimeKind.Local).AddTicks(9833),
                            From = "IAX",
                            Price = 249,
                            To = "FZB"
                        },
                        new
                        {
                            Id = 69,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 6, 22, 43, 299, DateTimeKind.Local).AddTicks(9209),
                            From = "QOR",
                            Price = 113,
                            To = "LZT"
                        },
                        new
                        {
                            Id = 70,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 23, 18, 47, DateTimeKind.Local).AddTicks(3715),
                            From = "OIT",
                            Price = 386,
                            To = "KUT"
                        },
                        new
                        {
                            Id = 71,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 17, 26, 10, 376, DateTimeKind.Local).AddTicks(4821),
                            From = "TZF",
                            Price = 467,
                            To = "SNW"
                        },
                        new
                        {
                            Id = 72,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 21, 9, 57, 8, DateTimeKind.Local).AddTicks(6314),
                            From = "OJD",
                            Price = 333,
                            To = "URM"
                        },
                        new
                        {
                            Id = 73,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 37, 1, 479, DateTimeKind.Local).AddTicks(3314),
                            From = "EEO",
                            Price = 455,
                            To = "YAL"
                        },
                        new
                        {
                            Id = 74,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 23, 23, 35, 424, DateTimeKind.Local).AddTicks(2074),
                            From = "TXE",
                            Price = 324,
                            To = "DMW"
                        },
                        new
                        {
                            Id = 75,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 20, 19, 58, 450, DateTimeKind.Local).AddTicks(4053),
                            From = "ZYB",
                            Price = 358,
                            To = "WNP"
                        },
                        new
                        {
                            Id = 76,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 22, 7, 18, 763, DateTimeKind.Local).AddTicks(3745),
                            From = "WTP",
                            Price = 382,
                            To = "GWH"
                        },
                        new
                        {
                            Id = 77,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 55, 34, 376, DateTimeKind.Local).AddTicks(5266),
                            From = "XWZ",
                            Price = 475,
                            To = "SWL"
                        },
                        new
                        {
                            Id = 78,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 23, 54, 40, 406, DateTimeKind.Local).AddTicks(7337),
                            From = "YLW",
                            Price = 126,
                            To = "GGC"
                        },
                        new
                        {
                            Id = 79,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 10, 6, 45, 102, DateTimeKind.Local).AddTicks(1035),
                            From = "AHP",
                            Price = 485,
                            To = "ZHN"
                        },
                        new
                        {
                            Id = 80,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 1, 2, 34, 864, DateTimeKind.Local).AddTicks(2996),
                            From = "HNB",
                            Price = 483,
                            To = "WKY"
                        },
                        new
                        {
                            Id = 81,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 9, 1, 43, 56, 874, DateTimeKind.Local).AddTicks(8182),
                            From = "LFC",
                            Price = 170,
                            To = "OYK"
                        },
                        new
                        {
                            Id = 82,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 9, 1, 33, 26, 528, DateTimeKind.Local).AddTicks(3687),
                            From = "QOM",
                            Price = 397,
                            To = "MEF"
                        },
                        new
                        {
                            Id = 83,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 0, 47, 25, 80, DateTimeKind.Local).AddTicks(5021),
                            From = "HYO",
                            Price = 164,
                            To = "KTU"
                        },
                        new
                        {
                            Id = 84,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 23, 27, 20, 764, DateTimeKind.Local).AddTicks(2947),
                            From = "KBA",
                            Price = 245,
                            To = "YHO"
                        },
                        new
                        {
                            Id = 85,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 8, 16, 48, 31, 995, DateTimeKind.Local).AddTicks(4232),
                            From = "MKI",
                            Price = 308,
                            To = "FTO"
                        },
                        new
                        {
                            Id = 86,
                            Airlines = "KLM",
                            DepartureTime = new DateTime(2023, 11, 9, 1, 2, 54, 83, DateTimeKind.Local).AddTicks(4328),
                            From = "TTI",
                            Price = 381,
                            To = "UDS"
                        },
                        new
                        {
                            Id = 87,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 9, 3, 34, 57, 463, DateTimeKind.Local).AddTicks(5641),
                            From = "EAL",
                            Price = 437,
                            To = "HKH"
                        },
                        new
                        {
                            Id = 88,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 9, 43, 428, DateTimeKind.Local).AddTicks(1034),
                            From = "ZRH",
                            Price = 436,
                            To = "XDO"
                        },
                        new
                        {
                            Id = 89,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 8, 18, 4, 47, 910, DateTimeKind.Local).AddTicks(6213),
                            From = "XBD",
                            Price = 243,
                            To = "ZXL"
                        },
                        new
                        {
                            Id = 90,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 40, 11, 641, DateTimeKind.Local).AddTicks(2268),
                            From = "FOY",
                            Price = 442,
                            To = "HFP"
                        },
                        new
                        {
                            Id = 91,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 21, 36, 24, 248, DateTimeKind.Local).AddTicks(3217),
                            From = "YFZ",
                            Price = 487,
                            To = "BJA"
                        },
                        new
                        {
                            Id = 92,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 9, 4, 17, 3, 393, DateTimeKind.Local).AddTicks(1003),
                            From = "DWP",
                            Price = 287,
                            To = "SZX"
                        },
                        new
                        {
                            Id = 93,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 23, 46, 33, 592, DateTimeKind.Local).AddTicks(6116),
                            From = "PED",
                            Price = 260,
                            To = "ZYB"
                        },
                        new
                        {
                            Id = 94,
                            Airlines = "Lufthansa",
                            DepartureTime = new DateTime(2023, 11, 9, 6, 28, 26, 507, DateTimeKind.Local).AddTicks(6196),
                            From = "RRM",
                            Price = 112,
                            To = "QBZ"
                        },
                        new
                        {
                            Id = 95,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 14, 10, 54, 335, DateTimeKind.Local).AddTicks(3618),
                            From = "GWR",
                            Price = 443,
                            To = "CAJ"
                        },
                        new
                        {
                            Id = 96,
                            Airlines = "LOT",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 11, 26, 556, DateTimeKind.Local).AddTicks(6206),
                            From = "GLP",
                            Price = 116,
                            To = "BUK"
                        },
                        new
                        {
                            Id = 97,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 15, 55, 40, 956, DateTimeKind.Local).AddTicks(6690),
                            From = "LZH",
                            Price = 437,
                            To = "YQS"
                        },
                        new
                        {
                            Id = 98,
                            Airlines = "Aeroflot",
                            DepartureTime = new DateTime(2023, 11, 8, 13, 35, 8, 634, DateTimeKind.Local).AddTicks(1073),
                            From = "CLU",
                            Price = 436,
                            To = "QSC"
                        },
                        new
                        {
                            Id = 99,
                            Airlines = "Turkish Airlines",
                            DepartureTime = new DateTime(2023, 11, 8, 11, 58, 58, 868, DateTimeKind.Local).AddTicks(7002),
                            From = "WME",
                            Price = 323,
                            To = "SDR"
                        },
                        new
                        {
                            Id = 100,
                            Airlines = "Ryanair",
                            DepartureTime = new DateTime(2023, 11, 8, 23, 10, 29, 31, DateTimeKind.Local).AddTicks(5560),
                            From = "OPW",
                            Price = 484,
                            To = "CPU"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
